---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/english/_index.md
  label: Homepage (en)
- type: directory
  path: exampleSite/content/english/blog
  label: Blog (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/english/about
  label: About (en)
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/english/training
  label: Farmer Training(en)
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: exampleSite/content/curent
  label: Current Projects (en)
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - project
- type: directory
  path: exampleSite/content/past
  label: Past Projects (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: document
  path: exampleSite/content/future
  label: Upcoming Projects
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.en.toml
  label: Menu (en)
- type: document
  path: exampleSite/config/_default/menus.fr.toml
  label: Menu (fr)
- type: directory
  path: exampleSite/i18n
  label: i18n Translations
  create: all
  match: "**/*"
upload_dir: pro-dev/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 1313 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.87.0
